[package]
name = "taskvisor"
version = "0.0.3"
edition = "2024"

description = "Event-driven task orchestration with restart, backoff, and user-defined observers"
repository = "https://github.com/soltiHQ/taskvisor"
documentation = "https://docs.rs/taskvisor"
license = "Apache-2.0"
readme = "README.md"

keywords = ["async", "tasks", "supervisor", "backoff", "orchestration"]
categories = ["asynchronous", "concurrency", "development-tools"]

[features]
default = []
logging = []
events = []

[package.metadata.docs.rs]
features = ["logging", "events"]

[dependencies]
tokio = { version = "1.47.1", features = ["rt-multi-thread", "macros", "time", "sync", "signal"] }
async-trait = "0.1.89"
tokio-util = "0.7.16"
thiserror = "2.0.16"
anyhow = "1.0.100"
log = "0.4.28"
futures = "0.3.31"

[[example]]
name = "simple_pipeline"
path = "examples/simple_pipeline.rs"
required-features = ["logging"]