version: '3'

includes:
  rust:
    taskfile: https://raw.githubusercontent.com/soltiHQ/actions/main/taskfiles/rust/Taskfile.yml
    vars:
      image_patch: "-1"

tasks:
  ci/fmt:
    desc: Run 'cargo fmt --check'.
    cmds:
      - task: rust:fmt

  ci/check:
    desc: Run 'cargo check'.
    cmds:
      - task: rust:check

  ci/clippy:
    desc: Run 'cargo clippy'.
    cmds:
      - task: rust:clippy

  ci/test:
    desc: Run 'cargo test'.
    cmds:
      - task: rust:test

  ci/audit:
    desc: Run 'cargo audit'.
    cmds:
      - task: rust:audit

  ci/bench:
    desc: Run 'cargo bench'.
    cmds:
      - task: rust:bench

  ci/docs:
    desc: Run 'rustdoc' for the taskvisor crate.
    cmds:
      - task: rust:docs
        vars:
          DOCS_ARGS: '--features "logging controller"'
