version: '3'

vars:
  git_root:
    sh: git rev-parse --show-toplevel

  rust_version: "1.90"

tasks:
  default:
    desc: Default task.
    cmds:
      - echo "Please enter a task or use '-l' or '--list-all' to list all available tasks"
    silent: true

  # ================================================#
  # ---------------------INTERNAL-------------------#
  # ================================================#

  _docker/run:
    desc: Internal task to run task in containers.
    internal: true
    silent: true
    requires:
      vars: [ IMAGE, CMD, MOUNT_DIR ]
    dir: "{{.git_root}}"
    cmd: |
      set -euo pipefail
      
      if ! docker image inspect "{{.IMAGE}}" >/dev/null 2>&1; then
        echo "pulling: {{.IMAGE}}"
      
        docker pull -q "{{.IMAGE}}" >/dev/null 2>&1 || {
          echo "Failed to pull image: {{.IMAGE}}"
          exit 1
        }
      fi

      docker run --rm --init --pull=never \
        --security-opt no-new-privileges \
        --user $(id -u):$(id -g) \
        --cap-drop=ALL \
        \
        --volume "{{.git_root}}/{{.MOUNT_DIR}}:/workspace:rw" \
        {{if .VOLUMES}}{{range $vol := .VOLUMES}}--volume {{$vol}} {{end}}\{{end}}
        {{if .ENVS}}{{range $env := .ENVS}}--env {{$env}} {{end}}\{{end}}
        --workdir /workspace \
        {{.IMAGE}} \
        {{.CMD}}

  _cargo/tool:
    internal: true
    silent: true
    requires:
      vars: [ CMD ]
    cmds:
      - task: _docker/run
        vars:
          IMAGE: "rust:{{.rust_version}}-slim"
          CMD: "{{.CMD}}"
          MOUNT_DIR: "."
          VOLUMES:
            - "{{.git_root}}/.cache/cargo:/tmp/cargo"
            - "{{.git_root}}/.cache/target:/tmp/target"
          ENVS:
            - "CARGO_TARGET_DIR=/tmp/target"
            - "CARGO_HOME=/tmp/cargo"
            - "CARGO_INCREMENTAL=0"

  # ================================================#
  # ----------------------PUBLIC--------------------#
  # ================================================#

  cargo/fmt:
    desc: Run 'cargo fmt'.
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "rustup component add rustfmt >/dev/null 2>&1 && cargo fmt --check --verbose"

  cargo/clippy:
    desc: Run 'cargo clippy'.
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "rustup component add clippy >/dev/null 2>&1 && cargo clippy --all --all-features -- -D warnings"

  cargo/test:
    desc: Run 'cargo test'.
    cmds:
      - task: _cargo/tool
        vars:
          CMD: "cargo test --all --all-features"
