name: Cache Put
description: Put cache to github

inputs:
  job_name:
    description: Job name for cache key
    required: true

runs:
  using: "composite"

  steps:
    - name: Debug before save
      shell: bash
      run: |
        echo "Current dir: $(pwd)"
        echo "Cargo.lock exists: $(test -f Cargo.lock && echo YES || echo NO)"
        echo "Cache dir size: $(du -sh .cache)"
        echo "Files in cache: $(find .cache -type f | wc -l)"

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: |
          .cache/cargo
          .cache/target
        key: ${{ inputs.job_name }}-hash-${{ hashFiles('**/Cargo.lock') }}