name: Cache Get
description: Get cache from GitHub

inputs:
  job_name:
    description: Job name for cache key
    required: true

outputs:
  cache-hit:
    description: Cache hit status
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Prepare cache dirs
      shell: bash
      run: mkdir -p .cache/cargo .cache/target

    - name: Restore cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: |
          .cache/cargo
          .cache/target
        key: job-${{ inputs.job_name }}-hash-${{ hashFiles('Cargo.lock') }}
