name: 'Cache Get'
description: 'Restore cache'
inputs:
  job_name:
    description: 'Job name for cache key'
    required: true
  rust_version:
    description: 'Rust version'
    default: '1.90'
outputs:
  cache-hit:
    description: 'Cache hit status'
    value: ${{ steps.cache.outputs.cache-hit }}
  cache-key:
    description: 'Generated cache key'
    value: ${{ steps.cache.outputs.cache-primary-key }}

runs:
  using: "composite"
  steps:
    - name: Prepare cache dirs with proper permissions
      shell: bash
      run: |
        mkdir -p .cache/cargo .cache/target
        chmod -R 777 .cache

    - name: Restore cache
      id: cache
      uses: actions/cache/restore@v4
      with:
        path: |
          .cache/cargo
          .cache/target
        key: ${{ inputs.job_name }}-cache-${{ runner.os }}-rust-${{ inputs.rust_version }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ inputs.job_name }}-cache-${{ runner.os }}-rust-${{ inputs.rust_version }}-

    - name: Fix permissions after restore
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        # Фиксим права после восстановления кэша
        chmod -R 777 .cache || true