name: Task Runner
description: Invoke Task commands

inputs:
  command:
    description: Task command to run
    required: true
  vars:
    description: Envs for command as key=value,key=value
    required: false
  dir:
    description: Working directory
    required: false
    default: '.'
  version:
    description: Version
    required: false
    default: '3.44.1'

runs:
  using: composite
  steps:
    - name: Cache Task binary
      id: cache
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/task
        key: task-${{ inputs.version }}-linux-amd64

    - name: Install Task
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        
        URL="https://github.com/go-task/task/releases/download/v${{ inputs.version }}/task_linux_amd64.tar.gz"
        curl -fsSL "$URL" | tar -xz task
        sudo install -m 755 task /usr/local/bin/task

    - name: Verify Task
      shell: bash
      run: task --version

    - name: Export environment variables
      if: ${{ inputs.vars != '' }}
      shell: bash
      run: |
        set -euo pipefail
        
        IFS=',' read -ra VARS <<< "${{ inputs.vars }}"
        for var in "${VARS[@]}"; do
          [[ "$var" =~ ^([^=]+)=(.+)$ ]] && echo "${BASH_REMATCH[1]}=${BASH_REMATCH[2]}" >> "$GITHUB_ENV"
        done

    - name: Run Task command
      shell: bash
      working-directory: ${{ inputs.dir }}
      run: |
        set -euo pipefail
        echo "🚀 Running task ${{ inputs.command }}"
        task ${{ inputs.command }}
