name: Build examples

on: { workflow_call: {} }

jobs:
  list:
    runs-on: ${{ vars.RUNS_ON }}
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - id: set
        shell: bash
        run: |
          entries=$(find examples -mindepth 1 -maxdepth 1 -type f -name '*.rs' -exec basename {} .rs \;)
          matrix=$(printf '%s\n' "$entries" | jq -Rsc 'split("\n") | map(select(length > 0))')
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build:
    needs: list
    runs-on: ${{ vars.RUNS_ON }}
    strategy:
      fail-fast: false
      matrix:
        example: ${{ fromJSON(needs.list.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - name: Build example
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci/build CRATE=${{ matrix.example }}
