name: Checks
on: { workflow_call: {} }

permissions: { contents: read, actions: write }

env:
  CI: "true"
  CARGO_TERM_COLOR: "always"
  RUST_BACKTRACE: "1"

jobs:
  test:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: Mad-Pixels/github-workflows/actions/taskfile-runner@v1
        with: { command: cargo/test }
