name: Checks
on: { workflow_call: {} }

permissions: {
  contents: read,
  actions: write
}

env:
  CI: "true"
  CARGO_TERM_COLOR: "always"
  RUST_BACKTRACE: "1"

jobs:
  fmt:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v4

      - name: Run fmt
        uses: ./.github/actions/taskfile
        with: { command: cargo/fmt }

  clippy:
    runs-on: ${{ vars.RUNS_ON }}
    concurrency:
      group: cache-${{ github.ref_name }}-clippy-${{ hashFiles('**/Cargo.lock') }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Get cache
        id: cache_get
        uses: ./.github/actions/cache-get
        with:
          job_name: clippy

      - name: Run clippy
        uses: ./.github/actions/taskfile
        with: { command: cargo/clippy }

      - name: Put cache
        if: steps.cache_get.outputs.matched-key != steps.cache_get.outputs.primary-key
        uses: ./.github/actions/cache-put
        with:
          job_name: clippy

  test:
    runs-on: ${{ vars.RUNS_ON }}
    concurrency:
      group: cache-${{ github.ref_name }}-clippy-${{ hashFiles('**/Cargo.lock') }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4

      - name: Get cache
        id: cache_get
        uses: ./.github/actions/cache-get
        with:
          job_name: test

      - name: Run tests
        uses: ./.github/actions/taskfile
        with: { command: cargo/test }

      - name: Put cache
        if: steps.cache_get.outputs.matched-key != steps.cache_get.outputs.primary-key
        uses: ./.github/actions/cache-put
        with:
          job_name: test
