name: Checks

on: { workflow_call: {} }

jobs:
  fmt:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run fmt
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/fmt }

  check:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run check
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/check }

  unittest:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cargo-cache
        with: { scope: unittest }
      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/test-unit }

  integration:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cargo-cache
        with: { scope: integration }
      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/test-integration }

  clippy:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cargo-cache
        with: { scope: clippy }
      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/clippy }
