name: Checks

on: { workflow_call: {} }

jobs:
  fmt:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run fmt
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci:cargo/fmt }

  check:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run check
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci:cargo/check }

  test:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6

      - name: Get Cache
        id: cache_get
        uses: soltiHQ/actions/cache-get@main
        with:
          paths: |
            .cache/cargo
            .cache/target
          key: job-test-${{ hashFiles('Cargo.toml', 'rust-toolchain.toml') }}

      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci:cargo/test }

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: soltiHQ/actions/cache-put@main
        with:
          paths: |
            .cache/cargo
            .cache/target
          key: job-test-${{ hashFiles('Cargo.toml', 'rust-toolchain.toml') }}

  clippy:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6

      - name: Get Cache
        id: cache_get
        uses: soltiHQ/actions/cache-get@main
        with:
          paths: |
            .cache/cargo
            .cache/target
          key: job-clippy-${{ hashFiles('Cargo.toml', 'rust-toolchain.toml') }}

      - name: Run Job
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci:cargo/clippy }

      - name: Put Cache
        if: steps.cache_get.outputs.cache-hit != 'true'
        uses: soltiHQ/actions/cache-put@main
        with:
          paths: |
            .cache/cargo
            .cache/target
          key: job-clippy-${{ hashFiles('Cargo.toml', 'rust-toolchain.toml') }}
