name: Docs

on: { workflow_call: {} }

jobs:
  docs:
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - uses: actions/checkout@v6
      - name: Run docs gen
        uses: soltiHQ/actions/taskfile@main
        with:
          command: ci:cargo/docs CRATE=taskvisor MANIFEST_PATH=Cargo.toml
