name: Docs

on: { workflow_call: {} }

jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Run docs gen
        uses: soltiHQ/actions/taskfile@main
        with: { command: ci/docs }
