name: Base commit

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: base-commit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

jobs:
  checks:
    name: (Base) Commit Checks
    uses: ./.github/workflows/.checks.yml

  commit-check:
    name: (Base) Commit Check
    needs: checks
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: All checks passed
        run: |
          echo "All Commit checks completed successfully!"
