name: Label

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

concurrency:
  group: label-${{ github.ref }}
  cancel-in-progress: true

permissions: {
  contents: read,
  pull-requests: read
}

jobs:
  label-check:
    name: Label check
    uses: soltiHQ/actions/.github/workflows/label-check.yml@v1
