name: PR action

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: pr-action-${{ github.ref }}
  cancel-in-progress: true

permissions: {
  contents: read,
  actions: write
}

jobs:
  ci:
    name: ci
    uses: soltiHQ/actions/.github/workflows/rust-ci.yml@v1

  docs:
    name: docs
    uses: soltiHQ/actions/.github/workflows/docs-ci.yml@v1
