name: Pr

on:
  pull_request:
    types: [labeled, synchronize, reopened]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions: {
  contents: read,
  actions: write,
  pull-requests: read
}

jobs:
  audit:
    name: Audit
    if: ${{ toJSON(github.event.pull_request.labels) != '[]' }}
    uses: ./.github/workflows/.audit.yml

  label-check:
    name: Label check
    if: ${{ toJSON(github.event.pull_request.labels) != '[]' }}
    uses: ./.github/workflows/.label-check.yml

  docs:
    name: Docs
    needs: [audit, label-check]
    uses: ./.github/workflows/.docs.yml

  build:
    name: Build examples
    needs: [audit, label-check]
    uses: ./.github/workflows/.build.yml

  preflight:
    name: Preflight
    needs: [audit, label-check]
    uses: ./.github/workflows/.preflight.yml

  pr-check:
    name: Pr Check
    needs: [audit, label-check, docs, build]
    runs-on: ${{ vars.RUNS_ON }}
    steps:
      - name: All checks passed
        run: echo "All Pr checks completed successfully!"
