name: Release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: false

permissions: {
  contents: write,
  actions: write
}

jobs:
  release:
    name: release
    uses: soltiHQ/actions/.github/workflows/rust-release.yml@v1
    with:
      crate: taskvisor
    secrets:
      crates-io-token: ${{ secrets.CRATES_IO_TOKEN }}
